-- snowflake_reset.sql
-- Use this to reset your Snowflake schemas before a clean demo.
-- Paste into a Snowflake worksheet, or run with snowsql.

-- optional, if your role differs:
-- USE ROLE ACCOUNTADMIN;

USE DATABASE ANJ_BD_PROJECT1;

-- Fast reset: drop & recreate schemas (CASCADE removes contained objects)
DROP SCHEMA IF EXISTS GOLD_LAYER_FRAUD   CASCADE;
DROP SCHEMA IF EXISTS SILVER_LAYER_FRAUD CASCADE;
DROP SCHEMA IF EXISTS BRONZE_LAYER_FRAUD CASCADE;

CREATE SCHEMA BRONZE_LAYER_FRAUD;
CREATE SCHEMA SILVER_LAYER_FRAUD;
CREATE SCHEMA GOLD_LAYER_FRAUD;

-- Alternatively, if you prefer to TRUNCATE instead of dropping schemas, use:
-- TRUNCATE TABLE IF EXISTS BRONZE_LAYER_FRAUD.USERS_BRONZE;
-- TRUNCATE TABLE IF EXISTS BRONZE_LAYER_FRAUD.PAYMENT_METHODS_BRONZE;
-- TRUNCATE TABLE IF EXISTS BRONZE_LAYER_FRAUD.TRANSACTIONS_BRONZE;
-- TRUNCATE TABLE IF EXISTS SILVER_LAYER_FRAUD.FRAUD_TRANSACTIONS_SILVER;
-- TRUNCATE TABLE IF EXISTS GOLD_LAYER_FRAUD.FRAUD_ANALYSIS_GOLD;
